sequence:
  class: File
  format: edam:format_1929
  location: ../../Data/16_retrieve_sequence_rice_down/rice_down_tmalign/blastdbcmd_result_rice_down_tmalign_rice.fasta

output_dir_name: sequence_rice_down_tmalign_rice