# re-execute the workflow date: 2025-05-26


INPUT_DIRECTORY:  # default value of type 'Directory'.
    class: Directory
    location: ../Data/12_rice_up_mmcif/

# FILE_MATCH_PATTERN: "*.cif"

# Download date: 2024-10-01
FOLDSEEK_INDEX: 
    class: File
    location: ../index/index_swissprot/swissprot
    secondaryFiles:
        - class: File
          location: ../index/index_swissprot/swissprot_ca
        - class: File
          location: ../index/index_swissprot/swissprot_ca.dbtype
        - class: File
          location: ../index/index_swissprot/swissprot_ca.index
        - class: File
          location: ../index/index_swissprot/swissprot_h
        - class: File
          location: ../index/index_swissprot/swissprot_h.dbtype
        - class: File
          location: ../index/index_swissprot/swissprot_h.index
        - class: File
          location: ../index/index_swissprot/swissprot_mapping
        - class: File
          location: ../index/index_swissprot/swissprot_ss
        - class: File
          location: ../index/index_swissprot/swissprot_ss.dbtype
        - class: File
          location: ../index/index_swissprot/swissprot_ss.index
        - class: File
          location: ../index/index_swissprot/swissprot_taxonomy
        - class: File
          location: ../index/index_swissprot/swissprot.dbtype
        - class: File
          location: ../index/index_swissprot/swissprot.index
        - class: File
          location: ../index/index_swissprot/swissprot.lookup
        - class: File
          location: ../index/index_swissprot/swissprot.version


OUTPUT_FILE_NAME1: "foldseek_output_uniprot_rice_up_all_evalue01.tsv"
EVALUE: 0.1
ALIGNMENT_TYPE: 2
THREADS: 16
SPLIT_MEMORY_LIMIT: "120G"
TAXONOMY_ID_LIST: "9606,10090,3702,4577,4529"

OUTPUT_FILE_NAME2: "foldseek_output_uniprot_rice_up_9606.tsv"

WF_COLUMN_NUMBER_QUERY_SPECIES: 1
WF_COLUMN_NUMBER_HIT_SPECIES: 2

OUTPUT_FILE_NAME_HIT_SPECIES: "foldseek_result_hit_species.txt"



SW_INPUT_FASTA_FILE_QUERY_SPECIES:
  class: File
  format: edam:format_1929
  location: ../Data/Data_uniprot/FASTA_for_index/uniprotkb_rice_all_250526.fasta

SW_INPUT_FASTA_FILE_HIT_SPECIES:
  class: File
  format: edam:format_1929
  location: ../Data/Data_uniprot/FASTA_for_index/uniprotkb_human_all_250526.fasta

ROUTE_DATASET: "uniprot,ensembl_protein,ensembl_transcript,ensembl_gene,hgnc,hgnc_symbol"

OUTPUT_FILE_NAME3: "foldseek_9606_togoid_convert.tsv"

OUT_NOTEBOOK_NAME: "plant2human_rice_up_report_20250526.ipynb"

QUERY_IDMAPPING_TSV:
  class: File
  format: edam:format_3475
  location: ../Data/12_rice_uniprot_idmapping/rice_up_idmapping_all.tsv


QUERY_GENE_LIST_TSV:  # default value of type 'File'.
    class: File
    format: edam:format_3475
    location: ../Data/rice_up_genelist.tsv





