index_files:
  class: File
  location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta
  secondaryFiles:
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pdb
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.phd
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.phi
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.phr
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pin
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pjs
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pog
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pos
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pot
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.psq
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.ptf
    - class: File
      location: ../../index/index_uniprot_rice/uniprotkb_rice_all_240820.fasta.pto
entry_batch:
  class: File
  location: ../../out/rice_down/rice_down_tmalign_result/uniprot_id_rice_down_tmalign.txt
retrieve_result_file_name: blastdbcmd_rice_down_tmalign.fasta
logfile_name: blastdbcmd_rice_down_tmalign.log