foldseek_extract_tsv:
  class: File
  format: edam:format_3475
  location: ../../out/rice_up/rice_up_tmalign_result/foldseek_rice_up_9606_tmalign.tsv
split_fasta_query_species_dir:
  class: Directory
  location: ../../out/rice_up/rice_up_tmalign_result/split_fasta_rice_up_tmalign/
split_fasta_hit_species_dir:
  class: Directory
  location: ../../out/rice_up/rice_up_tmalign_result/split_fasta_human_up_tmalign/
result_water_dir_name: "result_water_tmalign"
query_col_num: 2
target_col_num: 3
