# re-execute date: 2025-05-24

output_notebook_name: "rice_up_uniprot_idmapping_2505.ipynb"

gene_id_file:
  class: File
  format: edam:format_3475
  location: ../Data/07_extract_gene/HN5_genelist_rice_2505/HN5_genes_up_rice.tsv

uniprot_api_query_db: "Ensembl_Genomes"
uniprot_api_target_db: "UniProtKB"
json_dir_name: "12_rice_up_afinfo_json"
data_url: "cifUrl"
structure_dir_name: "12_rice_up_mmcif"
id_mapping_all_file_name: "rice_up_idmapping_all.tsv"