entry_batch:
  class: File
  location: ../../Data/15_foldseek_hit_idlist/uniprot_id_rice_up_tmalign_rice_idlist.txt

retrieve_result_file_name: blastdbcmd_result_rice_up_tmalign_rice.fasta
logfile_name: blastdbcmd_result_rice_up_tmalign_rice.log